#%Module1.0
module-whatis "Intel(R) Compiler Tools"
module-whatis "Version: VERSION"
module-whatis "Description: Intel Compiler Tools includes the following...
                       Intel(R) Parallel Studio XE Composer Edition for Linux
                       Intel(R) C++ Compiler XE for Linux
                       Intel(R) Fortran Compiler XE for Linux
                       Intel(R) Integrated Performance Primitives for Linux
                       Intel(R) Math Kernel Library for Linux
                       Intel(R) Threading Building Blocks for Linux"

# If unloading, also unload any intel-dependent modules
if {[module-info mode switch1] || [module-info mode switch3]} {
  # Get the command line that invoked this process; unload only if switching
  # from intel to another (compiler) module, e.g., "module switch intel gnu"
  set commandWords [split [exec /bin/ps -p [pid] -o args=] " "]
  set switchFrom [lindex [split [module-info name] "/"] 0]
  set switchTo [lindex [split [lindex $commandWords end] "/"] 0]
  set unloadApps [expr ! [string equal $switchTo $switchFrom]]
} elseif {[module-info mode remove]} {
  set unloadApps 1
} else {
  set unloadApps 0
}
if {$unloadApps && [info exists env(LOADEDMODULES)]} {
  foreach app [lreverse [split $env(LOADEDMODULES) ":"]] {
    if {[string first "intel/" $app] == 0} {
      continue
    }
    # Check whether this module references a compiler-specific subdir
    set moduleEffects [exec bash -c "module display $app" 2>@1]
    if {[string first "/intel" $moduleEffects] >= 0} {
      puts stderr "Unloading compiler-dependent module $app"
      module unload [lindex [split $app "/"] 0]
    }
  }
}

# Add all intel-dependent module dirs to the search path
foreach path [glob -nocomplain /opt/modulefiles/*/.intel] {
  prepend-path MODULEPATH $path
}

# Compiler environment modifications
set intelPrefix /opt/intel/VERSION
set versionYear [lindex [split VERSION .] 0]
set intelHome $intelPrefix/compilers_and_libraries_VERSION/linux
setenv INTELHOME $intelHome

prepend-path PATH $intelHome/bin/intel64
prepend-path MANPATH $intelPrefix/documentation_$versionYear/en/man/common
setenv TBBROOT $intelHome/tbb
prepend-path LD_LIBRARY_PATH $intelHome/compiler/lib/intel64_lin:$intelHome/ipp/../compiler/lib/intel64:$intelHome/ipp/lib/intel64:$intelHome/mkl/lib/intel64:$intelHome/tbb/lib/intel64/gcc4.4
setenv LIBRARY_PATH $intelHome/compiler/lib/intel64_lin:$intelHome/ipp/../compiler/lib/intel64:$intelHome/ipp/lib/intel64:$intelHome/mkl/lib/intel64:$intelHome/tbb/lib/intel64/gcc4.4
setenv INTEL_LICENSE_FILE $intelHome/licenses:/opt/intel/licenses:/root/intel/licenses
setenv MKL_ROOT $intelHome/mkl
setenv MKLROOT $intelHome/mkl
setenv IPPROOT $intelHome/ipp
setenv FPATH $intelHome/mkl/include
setenv CPATH $intelHome/ipp/include:$intelHome/mkl/include:$intelHome/tbb/include
setenv NLSPATH $intelHome/compiler/lib/intel64_lin/locale/%l_%t/%N:$intelPrefix/debugger_YEAR/gdb/intel64/share/locale/%l_%t/%N
setenv INCLUDE $intelHome/mkl/include
setenv GDBSERVER_MIC $intelPrefix/debugger_YEAR/gdb/targets/mic/bin/gdbserver

setenv MIC_LD_LIBRARY_PATH $intelHome/compiler/lib/mic:$intelHome/mkl/lib/mic:$intelHome/tbb/lib/mic
setenv MIC_LIBRARY_PATH $intelHome/compiler/lib/mic:$intelHome/tbb/lib/mic
setenv GDB_CROSS $intelHome/bin/intel64/gdb-mic
setenv MPM_LAUNCHER $intelPrefix/debugger_YEAR/mpm/intel64_igfx/bin/start_mpm.sh
setenv INTEL_PYTHONHOME $intelPrefix/debugger_YEAR/gdb/intel64/share/gdb/python
setenv INFOPATH $intelPrefix/documentation_YEAR/en/debugger/gdb-ia/info/:$intelPrefix/documentation_YEAR/en/debugger/gdb-mic/info
setenv L_MKL_TEMP   M_VERS
