REDHAT.ROOT = $(CURDIR)/../../

-include $(ROCKSROOT)/etc/Rules.mk
include Rules.mk
include $(SDSCDEVEL)/Rules.mk

$(VERSION_INC): $(VERSION_SRC)
	/bin/grep 'VERSION.*=' $(VERSION_SRC) > $@
 
build:

install::
	mkdir -p -m 755 $(ROOT)/$(PKGROOT)
	for V in $(VERSION) $(EXTRA_MODULE_VERSIONS); do \
          cp *.module $(ROOT)/$(PKGROOT)/$$V; \
          cp *.version $(ROOT)/$(PKGROOT)/.version.$$V; \
          perl -pi -e 's#COMPILERNAME#$(COMPILERNAME)#g;' \
                   -e 's#MPINAME#$(MPINAME)#g;' \
                   -e 's#ROLLCOMPILER#$(ROLLCOMPILER)#g;' \
                   -e 's#ROLLMPI#$(ROLLMPI)#g;' \
                   -e 's#ROLLOPTS#$(ROLLOPTS)#g;' \
                   -e 's#ROLLPY#$(ROLLPY)#g;' \
                   -e "s#VERSION#$$V#g;" \
            $(ROOT)/$(PKGROOT)/.version.$$V $(ROOT)/$(PKGROOT)/$$V; \
        done


clean::
	rm -f $(VERSION_INC)
